version: '3.8'

services:
  # -------------------- Postgres --------------------
  db:
    image: postgres:17.3
    container_name: db
    env_file:
      - ".env"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "127.0.0.1:${POSTGRES_PORT}:5432"
    networks:
      - my_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # -------------------- FastAPI Backend --------------------
  web:
    build: ./backend/
    container_name: web
    command: bash -c "uvicorn start:app --host 0.0.0.0 --port 8000 --log-level info"
    env_file:
      - ".env"
    ports:
      - "127.0.0.1:${WEB_PORT}:8000"
    networks:
      - my_network
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  # -------------------- Directus Admin --------------------
  directus:
    image: directus/directus:latest
    container_name: directus
    ports:
      - "127.0.0.1:${ADMIN_DIRECTUS_PORT}:8055"
    environment:
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      KEY: ${KEY}
      SECRET: ${SECRET}
      DB_CLIENT: postgres
      DB_HOST: db
      DB_PORT: ${POSTGRES_PORT}
      DB_DATABASE: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      PUBLIC_URL: ${PUBLIC_URL}
      DIRECTUS_PATH: /admin
    networks:
      - my_network
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  # -------------------- Nginx Frontend --------------------
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "127.0.0.1:80:80"
    networks:
      - my_network
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - web
    restart: unless-stopped

# -------------------- Сети --------------------
networks:
  my_network:
    driver: bridge

# -------------------- Volumes --------------------
volumes:
  postgres_data:
